import 'package:flutter/material.dart';
import '../ghibli_theme_data.dart';
import 'ghibli_palette.dart';

class GhibliPalettes {
  static const List<GhibliPalette> all = [
    // 1) Nausicaä of the Valley of the Wind (1984)
    GhibliPalette(
      id: 'wind_valley',
      label: 'Wind Valley',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFE6F2EF),
        surface: Color(0xFFF6FBFA),
        primary: Color(0xFF7FA8A2),
        onPrimary: Color(0xFF1F3A38),
        secondary: Color(0xFFB6D6CF),
        accent: Color(0xFFD3E9E5),
        text: Color(0xFF203836),
        textSoft: Color(0xFF5F7F79),
        divider: Color(0xFFCCE3DE),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF0F1F1E),
        surface: Color(0xFF172B29),
        primary: Color(0xFF9ED6CE),
        onPrimary: Color(0xFF0F1F1E),
        secondary: Color(0xFF5F8F88),
        accent: Color(0xFF3E6F6A),
        text: Color(0xFFEAF6F4),
        textSoft: Color(0xFFBFD9D4),
        divider: Color(0xFF243E3B),
      ),
    ),

    // 2) Castle in the Sky (1986)
    GhibliPalette(
      id: 'floating_castle',
      label: 'Floating Castle',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF6FAFF),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFF8FB4D9),
        onPrimary: Color(0xFF1F3A52),
        secondary: Color(0xFFCFE2F5),
        accent: Color(0xFFE9F3FB),
        text: Color(0xFF1C2F40),
        textSoft: Color(0xFF5C7285),
        divider: Color(0xFFE3EEF8),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF101A24),
        surface: Color(0xFF182635),
        primary: Color(0xFFB7D3EE),
        onPrimary: Color(0xFF101A24),
        secondary: Color(0xFF5A7FA6),
        accent: Color(0xFF3F5E7D),
        text: Color(0xFFEAF2FA),
        textSoft: Color(0xFFB8CBE0),
        divider: Color(0xFF273A50),
      ),
    ),

    // 3) Grave of the Fireflies (1988)
    GhibliPalette(
      id: 'ember_silence',
      label: 'Ember Silence',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFF7F4),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFB87C6A),
        onPrimary: Color(0xFF3A1F18),
        secondary: Color(0xFFE6B8AA),
        accent: Color(0xFFF6DDD6),
        text: Color(0xFF3A1F18),
        textSoft: Color(0xFF7A5046),
        divider: Color(0xFFF2E1DB),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF1C0F0C),
        surface: Color(0xFF2A1511),
        primary: Color(0xFFE6B8AA),
        onPrimary: Color(0xFF1C0F0C),
        secondary: Color(0xFF8A4A3A),
        accent: Color(0xFF6A352A),
        text: Color(0xFFF7EDEA),
        textSoft: Color(0xFFD8B9B1),
        divider: Color(0xFF3A1F18),
      ),
    ),

    // 4) My Neighbor Totoro (1988)
    GhibliPalette(
      id: 'forest_spirits',
      label: 'Forest Spirits',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF4FAF6),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFF8DBF9B),
        onPrimary: Color(0xFF1F3A2A),
        secondary: Color(0xFFCDE7D5),
        accent: Color(0xFFE7F3EB),
        text: Color(0xFF20382A),
        textSoft: Color(0xFF5E7D6A),
        divider: Color(0xFFE1F0E6),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF0E1A13),
        surface: Color(0xFF16261D),
        primary: Color(0xFFBFE7CC),
        onPrimary: Color(0xFF0E1A13),
        secondary: Color(0xFF5A8F6A),
        accent: Color(0xFF3F6F4E),
        text: Color(0xFFEAF7EF),
        textSoft: Color(0xFFBFD9C8),
        divider: Color(0xFF223A2C),
      ),
    ),

    // 5) Kiki's Delivery Service (1989)
    GhibliPalette(
      id: 'witch_breeze',
      label: 'Witch’s Breeze',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFF5F8),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFD98BA0),
        onPrimary: Color(0xFF4A1F2A),
        secondary: Color(0xFFF1C2CF),
        accent: Color(0xFFF9DEE6),
        text: Color(0xFF3A1A22),
        textSoft: Color(0xFF7A4A55),
        divider: Color(0xFFF4E0E6),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF1A0D12),
        surface: Color(0xFF27121A),
        primary: Color(0xFFF1B7C7),
        onPrimary: Color(0xFF1A0D12),
        secondary: Color(0xFF8A3F55),
        accent: Color(0xFF6A2F42),
        text: Color(0xFFF7E9ED),
        textSoft: Color(0xFFD8B7C1),
        divider: Color(0xFF3A1B26),
      ),
    ),

    // 6) Only Yesterday (1991)
    GhibliPalette(
      id: 'golden_memories',
      label: 'Golden Memories',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFFBF2),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFE3C27A),
        onPrimary: Color(0xFF4A3A1F),
        secondary: Color(0xFFF2E0B8),
        accent: Color(0xFFFFF1D8),
        text: Color(0xFF3A2F18),
        textSoft: Color(0xFF7A6A4A),
        divider: Color(0xFFF3E7D0),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF1A1408),
        surface: Color(0xFF261E0E),
        primary: Color(0xFFFFE0A6),
        onPrimary: Color(0xFF1A1408),
        secondary: Color(0xFF8A6A2F),
        accent: Color(0xFF6A4E1D),
        text: Color(0xFFF7F0E2),
        textSoft: Color(0xFFD7C8A5),
        divider: Color(0xFF3A2F14),
      ),
    ),

    // 7) Porco Rosso (1992)
    GhibliPalette(
      id: 'crimson_sky',
      label: 'Crimson Sky',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFF6F3),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFD97C4E),
        onPrimary: Color(0xFF4A2414),
        secondary: Color(0xFFF1B99E),
        accent: Color(0xFFFFE0D2),
        text: Color(0xFF3A1F16),
        textSoft: Color(0xFF7A4E3A),
        divider: Color(0xFFF3E2DA),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF1A0F0A),
        surface: Color(0xFF27150E),
        primary: Color(0xFFFFC4A3),
        onPrimary: Color(0xFF1A0F0A),
        secondary: Color(0xFF8A4A2F),
        accent: Color(0xFF6A3522),
        text: Color(0xFFF7ECE6),
        textSoft: Color(0xFFD8B9AD),
        divider: Color(0xFF3A2418),
      ),
    ),

    // 8) Ocean Waves (1993)
    GhibliPalette(
      id: 'ocean_letters',
      label: 'Ocean Letters',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF4FBFF),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFF7FB7C9),
        onPrimary: Color(0xFF16333B),
        secondary: Color(0xFFC9E6F0),
        accent: Color(0xFFE6F5FA),
        text: Color(0xFF183038),
        textSoft: Color(0xFF5D7B86),
        divider: Color(0xFFE1EFF4),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF0D1820),
        surface: Color(0xFF132431),
        primary: Color(0xFFB7E2F0),
        onPrimary: Color(0xFF0D1820),
        secondary: Color(0xFF4F7A8A),
        accent: Color(0xFF355B6A),
        text: Color(0xFFEAF4FA),
        textSoft: Color(0xFFBBD2DD),
        divider: Color(0xFF213849),
      ),
    ),

    // 9) Pom Poko (1994)
    GhibliPalette(
      id: 'woodland_mischief',
      label: 'Woodland Mischief',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF7FBF2),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFF9FC27A),
        onPrimary: Color(0xFF243A18),
        secondary: Color(0xFFD9EDC2),
        accent: Color(0xFFEEF7E2),
        text: Color(0xFF23321B),
        textSoft: Color(0xFF6B7D5A),
        divider: Color(0xFFE6F0D6),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF111A0D),
        surface: Color(0xFF1A2613),
        primary: Color(0xFFD4F0B2),
        onPrimary: Color(0xFF111A0D),
        secondary: Color(0xFF5E7A3F),
        accent: Color(0xFF445A2F),
        text: Color(0xFFF0F7E8),
        textSoft: Color(0xFFCFE0BF),
        divider: Color(0xFF283A1F),
      ),
    ),

    // 10) Whisper of the Heart (1995)
    GhibliPalette(
      id: 'quiet_dreams',
      label: 'Quiet Dreams',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFBF7FF),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFB6A6C9),
        onPrimary: Color(0xFF2E2340),
        secondary: Color(0xFFE3D9F0),
        accent: Color(0xFFF2ECFA),
        text: Color(0xFF2A2038),
        textSoft: Color(0xFF6C5B7A),
        divider: Color(0xFFEDE5F6),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF120E1A),
        surface: Color(0xFF1D1628),
        primary: Color(0xFFE2D3F2),
        onPrimary: Color(0xFF120E1A),
        secondary: Color(0xFF6A5A8A),
        accent: Color(0xFF4E3F6A),
        text: Color(0xFFF2ECFA),
        textSoft: Color(0xFFCFC2E0),
        divider: Color(0xFF2B223A),
      ),
    ),

    // 11) Princess Mononoke (1997)
    GhibliPalette(
      id: 'ancient_guardians',
      label: 'Ancient Guardians',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF5FAF3),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFF8F9E7A),
        onPrimary: Color(0xFF243018),
        secondary: Color(0xFFD6DFC7),
        accent: Color(0xFFEBF1E3),
        text: Color(0xFF1F2A18),
        textSoft: Color(0xFF5F6B56),
        divider: Color(0xFFE3EAD8),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF0F160D),
        surface: Color(0xFF172014),
        primary: Color(0xFFCFE0B8),
        onPrimary: Color(0xFF0F160D),
        secondary: Color(0xFF576A44),
        accent: Color(0xFF3E4E32),
        text: Color(0xFFF0F6EA),
        textSoft: Color(0xFFC7D3BC),
        divider: Color(0xFF25301F),
      ),
    ),

    // 12) My Neighbors the Yamadas (1999)
    GhibliPalette(
      id: 'simple_days',
      label: 'Simple Days',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFFAF6),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFC9B8A6),
        onPrimary: Color(0xFF3A2F24),
        secondary: Color(0xFFEADFD4),
        accent: Color(0xFFF6EFE8),
        text: Color(0xFF2A221B),
        textSoft: Color(0xFF6B5F54),
        divider: Color(0xFFEFE6DE),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF15110D),
        surface: Color(0xFF201A14),
        primary: Color(0xFFE8D9CB),
        onPrimary: Color(0xFF15110D),
        secondary: Color(0xFF7A695A),
        accent: Color(0xFF5A4A3E),
        text: Color(0xFFF7F0EA),
        textSoft: Color(0xFFD7C8BD),
        divider: Color(0xFF2F261F),
      ),
    ),

    // 13) Spirited Away (2001)
    GhibliPalette(
      id: 'spirit_bathhouse',
      label: 'Spirit Bathhouse',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFF7F0),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFE09C7A),
        onPrimary: Color(0xFF402318),
        secondary: Color(0xFFF3D1C0),
        accent: Color(0xFFFFE8DC),
        text: Color(0xFF2E1B12),
        textSoft: Color(0xFF7A5647),
        divider: Color(0xFFF3E1D6),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF1A120C),
        surface: Color(0xFF241810),
        primary: Color(0xFFFFD1B8),
        onPrimary: Color(0xFF1A120C),
        secondary: Color(0xFF8A5A3A),
        accent: Color(0xFF6A3F2A),
        text: Color(0xFFF7EFE9),
        textSoft: Color(0xFFD8C2B7),
        divider: Color(0xFF332318),
      ),
    ),

    // 14) The Cat Returns (2002)
    GhibliPalette(
      id: 'moonlit_cats',
      label: 'Moonlit Cats',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF6F7FF),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFF9AA0C9),
        onPrimary: Color(0xFF1F2340),
        secondary: Color(0xFFD9DCF2),
        accent: Color(0xFFEEF0FB),
        text: Color(0xFF1C2038),
        textSoft: Color(0xFF5B607A),
        divider: Color(0xFFE6E9F6),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF101220),
        surface: Color(0xFF171A2D),
        primary: Color(0xFFD0D6FF),
        onPrimary: Color(0xFF101220),
        secondary: Color(0xFF5A5F8A),
        accent: Color(0xFF3F4470),
        text: Color(0xFFF0F1FA),
        textSoft: Color(0xFFBFC3E0),
        divider: Color(0xFF22264A),
      ),
    ),

    // 15) Howl’s Moving Castle (2004)
    GhibliPalette(
      id: 'moving_hearth',
      label: 'Moving Hearth',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFF9F3),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFD9A07A),
        onPrimary: Color(0xFF3A2418),
        secondary: Color(0xFFF1D2BE),
        accent: Color(0xFFFFEBDD),
        text: Color(0xFF2E1C12),
        textSoft: Color(0xFF7A5A47),
        divider: Color(0xFFF3E3D6),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF16110C),
        surface: Color(0xFF221A12),
        primary: Color(0xFFFFD7BF),
        onPrimary: Color(0xFF16110C),
        secondary: Color(0xFF7A4A2F),
        accent: Color(0xFF5A3622),
        text: Color(0xFFF7F0EA),
        textSoft: Color(0xFFD8C3B5),
        divider: Color(0xFF322318),
      ),
    ),

    // 16) Tales from Earthsea (2006)
    GhibliPalette(
      id: 'shadow_earth',
      label: 'Shadow Earth',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF7F8F6),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFF9A9A8D),
        onPrimary: Color(0xFF2A2A24),
        secondary: Color(0xFFD9D9D1),
        accent: Color(0xFFEEF0EA),
        text: Color(0xFF24241F),
        textSoft: Color(0xFF6A6A60),
        divider: Color(0xFFE6E7E1),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF10110E),
        surface: Color(0xFF181A14),
        primary: Color(0xFFD2D2C7),
        onPrimary: Color(0xFF10110E),
        secondary: Color(0xFF5A5A4E),
        accent: Color(0xFF3F3F36),
        text: Color(0xFFF0F1EC),
        textSoft: Color(0xFFC6C7BE),
        divider: Color(0xFF24261F),
      ),
    ),

    // 17) Ponyo (2008)
    GhibliPalette(
      id: 'sea_child',
      label: 'Sea Child',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFF6FA),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFF09BB6),
        onPrimary: Color(0xFF3A1B26),
        secondary: Color(0xFFA6DCE8),
        accent: Color(0xFFFFE1EC),
        text: Color(0xFF2A1820),
        textSoft: Color(0xFF7A4C5A),
        divider: Color(0xFFF2E1EA),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF170B10),
        surface: Color(0xFF241019),
        primary: Color(0xFFFFB8D1),
        onPrimary: Color(0xFF170B10),
        secondary: Color(0xFF4F8A98),
        accent: Color(0xFF6A2F42),
        text: Color(0xFFF7E9EF),
        textSoft: Color(0xFFD8B7C5),
        divider: Color(0xFF321624),
      ),
    ),

    // 18) The Secret World of Arrietty (2010)
    GhibliPalette(
      id: 'tiny_home',
      label: 'Tiny Home',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF5FBF7),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFA6C9A6),
        onPrimary: Color(0xFF203A2A),
        secondary: Color(0xFFD9F0D9),
        accent: Color(0xFFEAF7EA),
        text: Color(0xFF1F2E24),
        textSoft: Color(0xFF5F7A6A),
        divider: Color(0xFFE2F0E6),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF0E1712),
        surface: Color(0xFF16241C),
        primary: Color(0xFFD2F0D2),
        onPrimary: Color(0xFF0E1712),
        secondary: Color(0xFF4E7A5A),
        accent: Color(0xFF3A5A44),
        text: Color(0xFFEAF7EF),
        textSoft: Color(0xFFC7E0D0),
        divider: Color(0xFF223528),
      ),
    ),

    // 19) From Up on Poppy Hill (2011)
    GhibliPalette(
      id: 'hilltop_letters',
      label: 'Hilltop Letters',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFFAF4),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFC9A67A),
        onPrimary: Color(0xFF3A2A18),
        secondary: Color(0xFFEBD8C0),
        accent: Color(0xFFFFEEDB),
        text: Color(0xFF2A2116),
        textSoft: Color(0xFF7A6347),
        divider: Color(0xFFF0E4D6),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF15100A),
        surface: Color(0xFF20170E),
        primary: Color(0xFFFFD9AD),
        onPrimary: Color(0xFF15100A),
        secondary: Color(0xFF7A5A35),
        accent: Color(0xFF5A4226),
        text: Color(0xFFF7F0E8),
        textSoft: Color(0xFFD8C8B7),
        divider: Color(0xFF2F2316),
      ),
    ),

    // 20) The Wind Rises (2013)
    GhibliPalette(
      id: 'rising_wind',
      label: 'Rising Wind',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF6FAFC),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFF9FB7C9),
        onPrimary: Color(0xFF1F3040),
        secondary: Color(0xFFD8E6F0),
        accent: Color(0xFFEAF3F8),
        text: Color(0xFF1A2833),
        textSoft: Color(0xFF5C7280),
        divider: Color(0xFFE2EDF4),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF0F1820),
        surface: Color(0xFF152232),
        primary: Color(0xFFD2E6F5),
        onPrimary: Color(0xFF0F1820),
        secondary: Color(0xFF4F6A7A),
        accent: Color(0xFF34505A),
        text: Color(0xFFEAF2FA),
        textSoft: Color(0xFFBBD0DD),
        divider: Color(0xFF223548),
      ),
    ),

    // 21) The Tale of the Princess Kaguya (2013)
    GhibliPalette(
      id: 'painted_moon',
      label: 'Painted Moon',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFF7FB),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFD9B7C9),
        onPrimary: Color(0xFF3A2230),
        secondary: Color(0xFFF1D9E4),
        accent: Color(0xFFFFEAF2),
        text: Color(0xFF2A1A22),
        textSoft: Color(0xFF7A5A66),
        divider: Color(0xFFF2E3EA),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF160E12),
        surface: Color(0xFF22151B),
        primary: Color(0xFFF2D0E2),
        onPrimary: Color(0xFF160E12),
        secondary: Color(0xFF6A4A5A),
        accent: Color(0xFF4F3544),
        text: Color(0xFFF7EDF3),
        textSoft: Color(0xFFD8C1CB),
        divider: Color(0xFF2F1F26),
      ),
    ),

    // 22) When Marnie Was There (2014)
    GhibliPalette(
      id: 'marsh_reflections',
      label: 'Marsh Reflections',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF5FBF8),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFF9FBFA6),
        onPrimary: Color(0xFF1F3326),
        secondary: Color(0xFFD7EBDD),
        accent: Color(0xFFEAF6EF),
        text: Color(0xFF1A2A20),
        textSoft: Color(0xFF5B7A66),
        divider: Color(0xFFE2EFE7),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF0F1712),
        surface: Color(0xFF16241C),
        primary: Color(0xFFD2F0DB),
        onPrimary: Color(0xFF0F1712),
        secondary: Color(0xFF4F7A5F),
        accent: Color(0xFF355A44),
        text: Color(0xFFEAF7F0),
        textSoft: Color(0xFFC1E0CF),
        divider: Color(0xFF22352A),
      ),
    ),

    // 23) Earwig and the Witch (2020)
    GhibliPalette(
      id: 'odd_workshop',
      label: 'Odd Workshop',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFFFF7FA),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFC9A6C2),
        onPrimary: Color(0xFF352034),
        secondary: Color(0xFFF0D9EC),
        accent: Color(0xFFFFEAF7),
        text: Color(0xFF2A1A28),
        textSoft: Color(0xFF7A5A74),
        divider: Color(0xFFF2E3F0),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF150F15),
        surface: Color(0xFF211721),
        primary: Color(0xFFEFD0EA),
        onPrimary: Color(0xFF150F15),
        secondary: Color(0xFF6A4A66),
        accent: Color(0xFF4F354E),
        text: Color(0xFFF7EDF7),
        textSoft: Color(0xFFD8C1D6),
        divider: Color(0xFF2E1F2E),
      ),
    ),

    // 24) The Boy and the Heron (2023)
    GhibliPalette(
      id: 'grey_heron',
      label: 'Grey Heron',
      light: GhibliThemeData(
        brightness: Brightness.light,
        background: Color(0xFFF7F9FB),
        surface: Color(0xFFFFFFFF),
        primary: Color(0xFFA6B2C1),
        onPrimary: Color(0xFF1E2A35),
        secondary: Color(0xFFDCE4EE),
        accent: Color(0xFFEEF3F8),
        text: Color(0xFF1A2430),
        textSoft: Color(0xFF5B6A7A),
        divider: Color(0xFFE4EBF2),
      ),
      dark: GhibliThemeData(
        brightness: Brightness.dark,
        background: Color(0xFF0F141A),
        surface: Color(0xFF161D26),
        primary: Color(0xFFD3DEEA),
        onPrimary: Color(0xFF0F141A),
        secondary: Color(0xFF556171),
        accent: Color(0xFF3A4452),
        text: Color(0xFFEEF3F8),
        textSoft: Color(0xFFBFC9D6),
        divider: Color(0xFF232D3A),
      ),
    ),
  ];

  static GhibliPalette byId(String id) => all.firstWhere((p) => p.id == id);
}
